import { useTranslations } from "next-intl";
import { SectionHeading } from "@/components/section-heading";
import { RevealSection } from "@/components/results/reveal-section";
import methodologyData from "@/lib/methodology-data.json";
import { formatNumber } from "@/lib/format";
import type { Locale } from "@/lib/format";
import type { MethodologyData } from "@/lib/methodology-types";

const data = methodologyData as MethodologyData;

export interface MethodologyDocumentProps {
  locale: Locale;
}

// The trust wedge's public face: every formula, threshold, and source cited
// below is read straight out of lib/methodology-data.json — generated by
// apps/api/scripts/export_methodology.py from the real engine modules, not
// retyped here. Static, no client JS: this is a document to be read, not an
// interactive surface, so it renders as a plain server component in the
// same section-grammar (SectionHeading + RevealSection's hairline rule) as
// the results document.
export function MethodologyDocument({ locale }: MethodologyDocumentProps) {
  const t = useTranslations("Methodology");
  const tRatios = useTranslations("Methodology.ratios");
  const tAltman = useTranslations("Methodology.riskModels.altman");
  const tPiotroski = useTranslations("Methodology.riskModels.piotroski");
  const tBeneish = useTranslations("Methodology.riskModels.beneish");
  const tScoring = useTranslations("Methodology.scoring");
  const tBenchmarks = useTranslations("Methodology.benchmarks");
  const tPrinciples = useTranslations("Methodology.principles");
  const tRiskModels = useTranslations("Methodology.riskModels");

  const num = (value: number, decimals = 2) => formatNumber(value, { locale, decimals });
  const pct = (value: number) => `${Math.round(value * 100)}%`;

  const unitLabel: Record<MethodologyData["ratios"][number]["unit"], string> = {
    x: tRatios("unitX"),
    "%": tRatios("unitPercent"),
    money: tRatios("unitMoney"),
  };

  return (
    <div className="mx-auto max-w-5xl space-y-10 px-6 py-10">
      <header className="space-y-4 border-b-2 border-ink pb-6">
        <h1 className="font-display text-3xl text-ink sm:text-4xl">{t("heading")}</h1>
        <p className="max-w-3xl text-ink-muted">{t("lede")}</p>
        <p className="font-mono text-xs text-ink-muted">
          {t("generatedNote", { sha: data.generated_from })}
        </p>
      </header>

      {/* Формулы коэффициентов ------------------------------------------ */}
      <RevealSection className="space-y-6">
        <SectionHeading>{tRatios("heading")}</SectionHeading>
        {data.category_order.map((category) => {
          const ratios = data.ratios.filter((r) => r.category === category);
          if (ratios.length === 0) return null;
          return (
            <div key={category} className="space-y-1">
              <SectionHeading level={3}>{data.category_labels[category]}</SectionHeading>
              <div className="divide-y divide-line border border-line">
                {ratios.map((r) => (
                  <div
                    key={r.key}
                    data-ratio-key={r.key}
                    className="flex flex-col gap-1 p-3 sm:flex-row sm:items-baseline sm:justify-between sm:gap-4"
                  >
                    <span className="text-ink">{r.name}</span>
                    <span className="font-mono text-sm text-ink-muted">
                      {r.formula}
                      <span className="ml-2 text-xs uppercase tracking-wide">
                        ({unitLabel[r.unit]})
                      </span>
                    </span>
                  </div>
                ))}
              </div>
            </div>
          );
        })}
      </RevealSection>

      {/* Модели риска ------------------------------------------------------ */}
      <RevealSection className="space-y-8">
        <SectionHeading>{tRiskModels("heading")}</SectionHeading>

        {/* Altman Z-Score */}
        <div className="space-y-3">
          <SectionHeading level={3}>{tAltman("heading")}</SectionHeading>
          <div className="grid gap-4 sm:grid-cols-2">
            {(["public", "private"] as const).map((variant) => {
              const v = data.altman[variant];
              return (
                <div key={variant} className="border border-line p-4" data-altman-variant={variant}>
                  <h4 className="font-display text-ink">
                    {tAltman(variant === "public" ? "publicHeading" : "privateHeading")}
                  </h4>
                  <p className="mt-1 text-sm text-ink-muted">
                    {tAltman(variant === "public" ? "publicNote" : "privateNote")}
                  </p>
                  <p className="mt-2 font-mono text-sm text-ink">{v.formula}</p>
                  <dl className="mt-3 space-y-1 font-mono text-xs text-ink-muted">
                    <div>
                      {tAltman("goodLabel")}: {tAltman("aboveThreshold", { value: num(v.thresholds.good) })}
                    </div>
                    <div>
                      {tAltman("greyLabel")}:{" "}
                      {tAltman("betweenThresholds", {
                        grey: num(v.thresholds.grey),
                        good: num(v.thresholds.good),
                      })}
                    </div>
                    <div>
                      {tAltman("criticalLabel")}: {tAltman("belowThreshold", { value: num(v.thresholds.grey) })}
                    </div>
                  </dl>
                </div>
              );
            })}
          </div>
          <p className="text-sm text-ink-muted">
            <span className="font-display text-ink">{tAltman("x2Heading")}. </span>
            {data.altman.x2_note}
          </p>
          <p className="text-sm text-ink-muted">
            <span className="font-display text-ink">{tAltman("bankingHeading")}. </span>
            {data.altman.banking_note}
          </p>
        </div>

        {/* Piotroski F-Score */}
        <div className="space-y-3">
          <SectionHeading level={3}>{tPiotroski("heading")}</SectionHeading>
          <h4 className="font-display text-sm text-ink">{tPiotroski("signalsHeading")}</h4>
          <ul className="grid gap-x-6 gap-y-1 text-sm text-ink sm:grid-cols-3">
            {data.piotroski.signals.map((s) => (
              <li key={s.key} data-piotroski-signal={s.key}>
                {s.name}
              </li>
            ))}
          </ul>
          <h4 className="font-display text-sm text-ink">{tPiotroski("bandsHeading")}</h4>
          <ul className="space-y-1 font-mono text-xs text-ink-muted">
            {data.piotroski.bands.map((b) => (
              <li key={b.label}>
                {b.label}: {tPiotroski("rangeLabel", { min: pct(b.min), max: pct(b.max) })}
              </li>
            ))}
          </ul>
        </div>

        {/* Beneish M-Score */}
        <div className="space-y-3">
          <SectionHeading level={3}>{tBeneish("heading")}</SectionHeading>
          <h4 className="font-display text-sm text-ink">{tBeneish("indicesHeading")}</h4>
          <div className="divide-y divide-line border border-line">
            {data.beneish.indices.map((idx) => (
              <div
                key={idx.key}
                data-beneish-index={idx.key}
                className="flex items-baseline justify-between gap-4 p-2 text-sm"
              >
                <span className="text-ink">{idx.name}</span>
                <span className="font-mono text-ink-muted">
                  {tBeneish("coefficientLabel")}: {num(idx.coefficient, 3)}
                </span>
              </div>
            ))}
          </div>
          <p className="font-mono text-sm text-ink">
            {tBeneish("formulaHeading")}: {data.beneish.formula}
          </p>
          <div className="space-y-2 border-l border-line pl-4" data-testid="beneish-policy">
            <h4 className="font-display text-sm text-ink">{tBeneish("policyHeading")}</h4>
            <p className="text-sm text-ink-muted">
              {tBeneish("policyNote", {
                min: data.beneish.policy.min_available,
                total: data.beneish.policy.total_indices,
              })}
            </p>
            <p className="text-xs text-ink-muted">
              <span className="uppercase tracking-wide">{tBeneish("exampleSubstitutedHeading")}: </span>
              {data.beneish.policy.example_substituted_disclosure}
            </p>
            <p className="text-xs text-ink-muted">
              <span className="uppercase tracking-wide">{tBeneish("exampleInsufficientHeading")}: </span>
              {data.beneish.policy.example_insufficient_disclosure}
            </p>
          </div>
          <dl className="space-y-1 font-mono text-xs text-ink-muted">
            <div>
              {tBeneish("flagHigh")}: m &gt; {num(data.beneish.thresholds.high)}
            </div>
            <div>
              {tBeneish("flagGrey")}: {num(data.beneish.thresholds.grey)} &lt; m ≤{" "}
              {num(data.beneish.thresholds.high)}
            </div>
            <div>
              {tBeneish("flagLow")}: m ≤ {num(data.beneish.thresholds.grey)}
            </div>
          </dl>
        </div>
      </RevealSection>

      {/* Балльная оценка --------------------------------------------------- */}
      <RevealSection className="space-y-6">
        <SectionHeading>{tScoring("heading")}</SectionHeading>

        <div className="space-y-2">
          <h4 className="font-display text-sm text-ink">{tScoring("healthBandsHeading")}</h4>
          <ul className="divide-y divide-line border border-line text-sm">
            {data.health_bands.bands.map((b) => (
              <li key={b.label} className="flex items-baseline justify-between gap-4 p-2">
                <span className="text-ink">{b.label}</span>
                <span className="font-mono text-ink-muted">
                  {num(b.min, 0)}–{num(b.max, 0)}
                </span>
              </li>
            ))}
          </ul>
          <p className="font-mono text-xs text-ink-muted">
            {data.health_bands.insufficient_data_label}
          </p>
        </div>

        <div className="space-y-2">
          <h4 className="font-display text-sm text-ink">{tScoring("categoryWeightingHeading")}</h4>
          <p className="text-sm text-ink-muted">{tScoring("categoryWeightingNote")}</p>
        </div>

        <div className="space-y-2">
          <h4 className="font-display text-sm text-ink">{tScoring("confidenceHeading")}</h4>
          <p className="text-sm text-ink-muted">{tScoring("confidenceWeightsIntro")}</p>
          <ul className="font-mono text-xs text-ink-muted">
            <li>
              {tScoring("dataCompletenessLabel")}: {pct(data.confidence.weights.data_completeness)}
            </li>
            <li>
              {tScoring("extractionConfidenceLabel")}: {pct(data.confidence.weights.extraction_confidence)}
            </li>
            <li>
              {tScoring("ratioCoverageLabel")}: {pct(data.confidence.weights.ratio_coverage)}
            </li>
          </ul>
          <ul className="font-mono text-xs text-ink-muted">
            <li>
              {tScoring("bonusHasPreviousPeriod")}: +{data.confidence.bonuses.has_previous_period}
            </li>
            <li>
              {tScoring("bonusHasIndustryBenchmarks")}: +{data.confidence.bonuses.has_industry_benchmarks}
            </li>
            <li>
              {tScoring("bonusAudited")}: +{data.confidence.bonuses.audited}
            </li>
          </ul>
        </div>
      </RevealSection>

      {/* Отраслевые ориентиры ----------------------------------------------- */}
      <RevealSection className="space-y-6">
        <SectionHeading>{tBenchmarks("heading")}</SectionHeading>

        <div className="space-y-2">
          <h4 className="font-display text-sm text-ink">{tBenchmarks("perIndustryHeading")}</h4>
          <div className="overflow-x-auto border border-line">
            <table className="w-full text-left text-sm">
              <tbody className="divide-y divide-line">
                {data.benchmarks.per_industry.map((ind) => (
                  <tr key={ind.id} data-industry-id={ind.id}>
                    <td className="p-2 text-ink">{ind.name}</td>
                    <td className="p-2 font-mono text-xs text-ink-muted whitespace-nowrap">
                      {tBenchmarks("sourcedLabel")}: {ind.sourced_count}{" "}
                      {tBenchmarks("ofTotalLabel", { total: ind.sourced_count + ind.demo_count })}
                    </td>
                    <td className="p-2 font-mono text-xs text-ink-muted whitespace-nowrap">
                      {tBenchmarks("demoLabel")}: {ind.demo_count}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className="space-y-2">
          <h4 className="font-display text-sm text-ink">{tBenchmarks("sourcesHeading")}</h4>
          <ol className="space-y-1 font-mono text-xs text-ink-muted">
            {data.benchmarks.sources.map((s) => (
              <li key={s.url}>
                {s.source} ({s.as_of}) —{" "}
                <a href={s.url} className="underline hover:text-ink">
                  {s.url}
                </a>
              </li>
            ))}
          </ol>
        </div>

        <div className="space-y-2">
          <h4 className="font-display text-sm text-ink">{tBenchmarks("bandMethodHeading")}</h4>
          <p className="text-sm text-ink-muted">{data.benchmarks.band_method_note}</p>
        </div>
      </RevealSection>

      {/* Принципы (closing) -------------------------------------------------- */}
      <RevealSection>
        <section className="border-2 border-ink p-6">
          <h2 className="font-display text-xl text-ink">{tPrinciples("heading")}</h2>
          <ul className="mt-3 space-y-2 text-sm text-ink-muted">
            <li>{tPrinciples("determinism")}</li>
            <li>{tPrinciples("noLlmInNumbers")}</li>
            <li>{tPrinciples("naDiscipline")}</li>
          </ul>
        </section>
      </RevealSection>
    </div>
  );
}
