// TypeScript mirror of apps/web/lib/methodology-data.json's shape, which is
// itself generated by apps/api/scripts/export_methodology.py straight off
// the real engine modules (see that script's own header comment). This
// file only describes the JSON's shape — it never re-types a value.

export interface MethodologyRatio {
  key: string;
  name: string;
  category: string;
  formula: string;
  unit: "x" | "%" | "money";
}

export interface AltmanVariant {
  name: string;
  formula: string;
  thresholds: { good: number; grey: number };
}

export interface MethodologyAltman {
  public: AltmanVariant;
  private: AltmanVariant;
  x2_note: string;
  banking_note: string;
}

export interface PiotroskiSignalDef {
  key: string;
  name: string;
}

export interface PiotroskiBand {
  label: string;
  min: number;
  max: number;
}

export interface MethodologyPiotroski {
  signals: PiotroskiSignalDef[];
  bands: PiotroskiBand[];
}

export interface BeneishIndexDef {
  key: string;
  name: string;
  coefficient: number;
}

export interface BeneishPolicy {
  min_available: number;
  total_indices: number;
  neutral_substitution: Record<string, number>;
  example_substituted_disclosure: string;
  example_insufficient_disclosure: string;
}

export interface MethodologyBeneish {
  indices: BeneishIndexDef[];
  formula: string;
  intercept: number;
  policy: BeneishPolicy;
  thresholds: { high: number; grey: number };
}

export interface HealthBand {
  label: string;
  min: number;
  max: number;
}

export interface MethodologyHealthBands {
  bands: HealthBand[];
  insufficient_data_label: string;
}

export interface MethodologyConfidence {
  weights: {
    data_completeness: number;
    extraction_confidence: number;
    ratio_coverage: number;
  };
  bonuses: {
    has_previous_period: number;
    has_industry_benchmarks: number;
    audited: number;
  };
}

export interface BenchmarkIndustrySummary {
  id: string;
  name: string;
  sourced_count: number;
  demo_count: number;
}

export interface BenchmarkSource {
  source: string;
  as_of: string;
  url: string;
}

export interface MethodologyBenchmarks {
  per_industry: BenchmarkIndustrySummary[];
  sources: BenchmarkSource[];
  band_method_note: string;
}

export interface MethodologyData {
  ratios: MethodologyRatio[];
  category_labels: Record<string, string>;
  category_order: string[];
  altman: MethodologyAltman;
  piotroski: MethodologyPiotroski;
  beneish: MethodologyBeneish;
  health_bands: MethodologyHealthBands;
  confidence: MethodologyConfidence;
  benchmarks: MethodologyBenchmarks;
  generated_from: string;
  generated_at: string;
}
